# Generated by Django 5.1.1 on 2024-09-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_participant1', models.IntegerField(default=0)),
                ('score_participant2', models.IntegerField(default=0)),
                ('round', models.CharField(choices=[('Quart de finale', 'Quart de finale'), ('Demi-finale', 'Demi-finale'), ('Finale', 'Finale')], default='Quart de finale', max_length=20)),
                ('gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_gagnant', to='tournaments.joueur')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participant1', to='tournaments.joueur')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participant2', to='tournaments.joueur')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_in_tournoi', to='tournaments.tournoi')),
            ],
        ),
    ]
